### PR TITLE
updated to Flask SQLAchemy 2.5.1 and SQLAlchemy 1.4.3

### PR DESCRIPTION
**Pull request by blulady**

### CODE REVIEW

**Comment by p2635** [comment]
Thank you so much Sarah, I was wasting like 5 hours on this one issue.

**Comment by p2635** [comment]
@blulady just so I can learn from you, how did you diagnose that issue? If it was me, I would never be able to get to that conclusion since I'm a noob. Did you just try different older versions until it worked?

**Comment by automationhacks** [comment]
Hi @blulady : Can you please add more details on what issue were you facing and how these version bumps helped?

**Comment by p2635** [comment]
The issue is the build_database.py failed to run for me, but it was weeks ago when I did this so I don't remember all the details.

**Pull request merged**
